// Generated by QGIS: Export Themes UNION to Leaflet

function downloadGeoJSON(varName, fileName){
  var obj = window[varName];
  if(!obj){ alert('GeoJSON not loaded'); return; }
  var text = JSON.stringify(obj);
  var blob = new Blob([text], {type: 'application/geo+json'});
  var url = URL.createObjectURL(blob);
  var a = document.createElement('a');
  a.href = url;
  a.download = fileName || 'layer.geojson';
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(function(){ URL.revokeObjectURL(url); }, 1000);
}

function escapeHtml(s){
  if(s===null||s===undefined) return '';
  return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
}
function popupTable(props){
  var html = '<table class="popup">';
  for (var k in props){
    if(!Object.prototype.hasOwnProperty.call(props,k)) continue;
    if(k==='__style' || k==='__tooltip') continue;
    var v = props[k];
    if(typeof v === 'object') v = JSON.stringify(v);
    html += '<tr><th>' + escapeHtml(k) + '</th><td>' + escapeHtml(v) + '</td></tr>';
  }
  html += '</table>';
  return html;
}

var THEME_TITLE = "מפת רשת";
var MAP_MIN_ZOOM = 9;
var MAP_MAX_ZOOM = 18;

var map = L.map('map', {minZoom: MAP_MIN_ZOOM, maxZoom: MAP_MAX_ZOOM});
L.control.scale({imperial: false}).addTo(map);
map.createPane('vectorPane');
map.getPane('vectorPane').style.zIndex = 100;  // vectors BELOW ALL
map.createPane('bgPane');
map.getPane('bgPane').style.zIndex = 150;
map.createPane('basePane');
map.getPane('basePane').style.zIndex = 200;    // rasters ABOVE ALL
map.createPane('highlightPane');
map.getPane('highlightPane').style.zIndex = 250; // highlighted vectors ABOVE rasters

function enforceZoomLimits(){
  map.setMinZoom(MAP_MIN_ZOOM);
  map.setMaxZoom(MAP_MAX_ZOOM);
  var z = map.getZoom();
  if(z < MAP_MIN_ZOOM) map.setZoom(MAP_MIN_ZOOM);
  if(z > MAP_MAX_ZOOM) map.setZoom(MAP_MAX_ZOOM);
}

var EXPORT_BOUNDS = L.latLngBounds([[31.753631496725546,34.886055526729315],[31.984852949602196,35.14807205817312]]);

var vectorLayers = {};
var currentVectorId = null;
var baseLayers = {};
var baseMeta = {};
var currentBaseId = null;

var bgLayers = {};
var bgCurrentId = null;

var BG_SOURCES = [{"id":"openstreetmap","name":"OpenStreetMap","url":"https://tile.openstreetmap.org/{z}/{x}/{y}.png","maxNativeZoom":20},{"id":"waze","name":"WAZE","url":"https://il-livemap-tiles3.waze.com/tiles/{z}/{x}/{y}.png","maxNativeZoom":20},{"id":"google_satellite","name":"Google Satellite","url":"https://mt1.google.com/vt/lyrs=s&x={x}&y={y}&z={z}","maxNativeZoom":20}];

BG_SOURCES.forEach(function(b){
  bgLayers[b.id] = L.tileLayer(b.url, {
    pane: 'bgPane',
    minZoom: MAP_MIN_ZOOM, maxZoom: MAP_MAX_ZOOM,
    maxNativeZoom: b.maxNativeZoom || 19
  });
});

function setBackground(id){
  if(bgCurrentId && bgLayers[bgCurrentId]) map.removeLayer(bgLayers[bgCurrentId]);
  bgCurrentId = id;
  if(id && bgLayers[id]) bgLayers[id].addTo(map);
}

vectorLayers['layer_2021'] = L.geoJSON(geojson_layer_2021_2026_03_27, {
  pane: 'vectorPane',
  style: function(feature) {
    return (feature.properties && feature.properties.__style) ? feature.properties.__style : {};
  },
  pointToLayer: function(feature, latlng) {
    var st = (feature.properties && feature.properties.__style) ? feature.properties.__style : {};
    return L.circleMarker(latlng, st, { pane: 'vectorPane' });
  },
  onEachFeature: function(feature, layer) {
    if(feature.properties) layer.bindPopup(popupTable(feature.properties));
    if(feature.properties && feature.properties.__tooltip) {
      layer.bindTooltip(String(feature.properties.__tooltip), {sticky: true});
    }
  }
});
function setBase(id){
  if(currentBaseId && baseLayers[currentBaseId]) map.removeLayer(baseLayers[currentBaseId]);
  currentBaseId = id;
  if(id && baseLayers[id]) baseLayers[id].addTo(map);
  enforceZoomLimits();
}

var currentVectorId = null;

function setVectorExclusive(id){
  // remove all vector layers
  Object.keys(vectorLayers).forEach(function(k){
    var lyr = vectorLayers[k];
    if(lyr && map.hasLayer(lyr)) map.removeLayer(lyr);
  });
  currentVectorId = id;
  if(id && vectorLayers[id]) vectorLayers[id].addTo(map);
}

// Init: display only the first vector layer (if exists)
var __vkeys = Object.keys(vectorLayers);
if(__vkeys.length){
  currentVectorId = __vkeys[0];
  setVectorExclusive(currentVectorId);
}

map.fitBounds(EXPORT_BOUNDS);
enforceZoomLimits();

var VECTOR_TREE = [{"type": "layer", "layerId": "__________________________________________2021__b6476df0_f3a9_4ea5_9a80_d160a7d05b62", "id": "layer_2021", "name": "צפיפות תושבים לדונם נורמטיבי (נתוני למ\"ס 2021) ", "varName": "geojson_layer_2021_2026_03_27", "jsfile": "js/layer_2021_2026-03-27.geojson.js", "downloadName": "צפיפות תושבים לדונם נורמטיבי (נתוני למ_ס 2021)_2026-03-27.geojson", "legend": [{"label": "0 - 10", "icon": "legend/layer_2021_0.png"}, {"label": "10 - 20", "icon": "legend/layer_2021_1.png"}, {"label": "20 - 30", "icon": "legend/layer_2021_2.png"}, {"label": "30 - 40", "icon": "legend/layer_2021_3.png"}, {"label": "40+", "icon": "legend/layer_2021_4.png"}]}];
var RASTER_TREE = [];

function firstBaseId(){
  var keys = Object.keys(baseLayers);
  return keys.length ? keys[0] : null;
}
function firstBgId(){
  return (BG_SOURCES && BG_SOURCES.length) ? BG_SOURCES[0].id : null;
}
setBackground(firstBgId());
setBase(firstBaseId());

var highlightLayer = null;
map.on('popupopen', function(e) {
  var src = e.popup._source;
  if(src && src.feature) {
    if(highlightLayer) map.removeLayer(highlightLayer);
    highlightLayer = L.geoJSON(src.feature, {
      pane: 'highlightPane',
      style: { color: '#00FFFF', weight: 4, opacity: 1, fillColor: '#00FFFF', fillOpacity: 0.5 },
      pointToLayer: function(f, ll) {
        return L.circleMarker(ll, { pane: 'highlightPane', radius: 6, color: '#00FFFF', weight: 3, fillColor: '#00FFFF', fillOpacity: 0.5 });
      }
    }).addTo(map);
  }
});
map.on('popupclose', function(e) {
  if(highlightLayer) {
    map.removeLayer(highlightLayer);
    highlightLayer = null;
  }
});

document.getElementById('sidebar-title').innerText = THEME_TITLE;

function renderVectorLayer(node, container){
  var row=document.createElement('div'); row.className='row';
  var rb=document.createElement('input');
  rb.type='radio';
  rb.name='vectorOne';
  rb.value=node.id;
  rb.id='vec_' + node.id;
  rb.checked = (currentVectorId === node.id);
  rb.addEventListener('change', function(){
    if(rb.checked) setVectorExclusive(node.id);
  });
  row.appendChild(rb);
  var lab=document.createElement('label');
  lab.htmlFor='vec_' + node.id;
  lab.appendChild(document.createTextNode(node.name));
  row.appendChild(lab);
  var dl=document.createElement('a'); dl.className='download-link'; dl.href='#'; dl.title='הורדת GeoJSON'; dl.innerText='⬇';
  dl.addEventListener('click', function(e){ e.preventDefault(); downloadGeoJSON(node.varName, node.downloadName); });
  row.appendChild(dl);
  container.appendChild(row);
  if(node.legend && node.legend.length){
    var legend=document.createElement('div'); legend.className='legend-items';
    node.legend.forEach(function(li){
      var it=document.createElement('div'); it.className='legend-item';
      var img=document.createElement('img'); img.src=li.icon; img.alt='';
      var txt=document.createElement('div'); txt.innerText=li.label||'';
      it.appendChild(img); it.appendChild(txt); legend.appendChild(it);
    });
    container.appendChild(legend);
  }
}

function renderVectorGroup(node, container){
  var div=document.createElement('div'); div.className='node';
  var header=document.createElement('div'); header.className='row';
  var title=document.createElement('div'); title.className='group-title'; title.appendChild(document.createTextNode(node.name||'Group'));
  header.appendChild(title); div.appendChild(header);
  var inner=document.createElement('div'); inner.className='indent'; div.appendChild(inner);
  container.appendChild(div);
  if(node.children){ node.children.forEach(function(ch){
    if(ch.type==='group') renderVectorGroup(ch, inner);
    else renderVectorLayer(ch, inner);
  }); }
}

function renderRasterLayer(node, container){
  var row=document.createElement('div'); row.className='row';
  var rb=document.createElement('input'); rb.type='radio'; rb.name='baseRaster'; rb.value=node.id;
  rb.id='ras_' + node.id;
  rb.checked = (currentBaseId===node.id);
  rb.addEventListener('change', function(){ if(rb.checked) setBase(node.id); });
  var lab=document.createElement('label');
  lab.htmlFor='ras_' + node.id;
  lab.appendChild(document.createTextNode(node.name));
  row.appendChild(rb); row.appendChild(lab);
  container.appendChild(row);
  var under=document.createElement('div'); under.className='opacity-under';
  var slider=document.createElement('input'); slider.type='range'; slider.min='0'; slider.max='100'; slider.step='1';
  var cur = (baseMeta[node.id] && baseMeta[node.id].opacity!=null) ? baseMeta[node.id].opacity : 1.0;
  slider.value = Math.round(cur*100);
  slider.addEventListener('input', function(){
    var op = parseInt(slider.value,10)/100.0;
    if(baseMeta[node.id]) baseMeta[node.id].opacity = op;
    if(baseLayers[node.id] && baseLayers[node.id].setOpacity) baseLayers[node.id].setOpacity(op);
  });
  under.appendChild(slider);
  container.appendChild(under);
  if(node.legend && node.legend.length){
    var legend=document.createElement('div'); legend.className='legend-items legend-items-base';
    node.legend.forEach(function(li){
      var it=document.createElement('div'); it.className='legend-item';
      var img=document.createElement('img'); img.src=li.icon; img.alt='';
      var txt=document.createElement('div'); txt.innerText=li.label||'';
      it.appendChild(img); it.appendChild(txt); legend.appendChild(it);
    });
    container.appendChild(legend);
  }
}

function renderRasterGroup(node, container){
  var div=document.createElement('div'); div.className='node';
  var title=document.createElement('div'); title.className='group-title'; title.innerText = node.name || 'Group';
  div.appendChild(title);
  var inner=document.createElement('div'); inner.className='indent'; div.appendChild(inner);
  container.appendChild(div);
  if(node.children){ node.children.forEach(function(ch){
    if(ch.type==='group') renderRasterGroup(ch, inner);
    else renderRasterLayer(ch, inner);
  }); }
}

function renderBgRadios(container){
  if(!BG_SOURCES || !BG_SOURCES.length) return;
  BG_SOURCES.forEach(function(b){
    var row=document.createElement('div'); row.className='row';
    var rb=document.createElement('input'); rb.type='radio'; rb.name='bgBase'; rb.value=b.id;
    rb.id='bg_' + b.id;
    rb.checked = (bgCurrentId===b.id);
    rb.addEventListener('change', function(){ if(rb.checked) setBackground(b.id); });
    var lab=document.createElement('label');
    lab.htmlFor='bg_' + b.id;
    lab.appendChild(document.createTextNode(b.name));
    row.appendChild(rb); row.appendChild(lab);
    container.appendChild(row);
  });
}

function buildSidebar(){
  var vecDiv=document.getElementById('vector-tree');
  var rasDiv=document.getElementById('raster-tree');
  var bgDiv=document.getElementById('bg-tree');
  vecDiv.innerHTML=''; rasDiv.innerHTML=''; bgDiv.innerHTML='';
  RASTER_TREE.forEach(function(n){ if(n.type==='group') renderRasterGroup(n, rasDiv); else renderRasterLayer(n, rasDiv); });
  VECTOR_TREE.forEach(function(n){ if(n.type==='group') renderVectorGroup(n, vecDiv); else renderVectorLayer(n, vecDiv); });
  renderBgRadios(bgDiv);
  
  // הסתרת כותרות אם הרשימות ריקות מתוכן
  if (rasDiv.innerHTML.trim() === '') document.getElementById('raster-title').style.display = 'none';
  if (vecDiv.innerHTML.trim() === '') document.getElementById('vector-title').style.display = 'none';
  if (bgDiv.innerHTML.trim() === '') document.getElementById('bg-title').style.display = 'none';
}

buildSidebar();
